Userdashboard
Akshay-Tomar-1135/suraksha-frontend pull request #14
Opened 2024-10-13 05:06 UTC by adityaS-99

Made Changes to user contacts dashboard, implemented new location dashboard and lastly added profile page

2024-10-18 11:20 UTC, Akshay-Tomar-1135 commented on src/sections/location/location-table-head.tsx
> +        </TableCell> */}
remove unnecessary comments
if this is useful for future reference then leave it

2024-10-18 11:22 UTC, Akshay-Tomar-1135 commented on src/sections/location/location-table-head.tsx
> +  // onSelectAllRows: (checked: boolean) => void;
remove unnecessary comments

2024-10-18 11:23 UTC, Akshay-Tomar-1135 commented on src/sections/location/location-table-row.tsx
> +};
if these are to display user details, then instead of this take reference from updated code and use redux states, defined to store user info.

2024-10-18 11:24 UTC, Akshay-Tomar-1135 commented on src/sections/location/location-table-row.tsx
> +        </TableCell> */}
remove unnecessary comments

2024-10-18 11:28 UTC, Akshay-Tomar-1135 commented on src/sections/location/view/location-view.tsx
> +        </Button> */}
comment

2024-10-18 11:28 UTC, Akshay-Tomar-1135 commented on src/sections/location/view/location-view.tsx
> +                      // onSelectRow={() => table.onSelectRow(row.id)}
comment

2024-10-18 11:31 UTC, Akshay-Tomar-1135 commented on src/sections/profile/view/profile-view.tsx
> +  });
from the updated code in develop, use redux states defined for user info

2024-10-18 11:34 UTC, Akshay-Tomar-1135 commented on src/sections/user/user-add-modal.tsx
> +// isVerified = email
remove unnecessary comments

2024-10-18 11:37 UTC, Akshay-Tomar-1135 commented on src/sections/user/user-edit-modal.tsx
> +  const [snackbarSeverity, setSnackbarSeverity] = useState<'success' | 'error'>('success'); // Snackbar severity
You can remove these snackbar implementation,
As I have added snackbar globally in updated code
You can take reference from ```src/sections/auth/auth-view.tsx```

2024-10-18 11:42 UTC, Akshay-Tomar-1135 commented on src/sections/user/user-edit-modal.tsx
> +        const result = await updateUserContact(user.role, {
declare this updateUserContact service in ```src/services/userService.ts```
how to use the service, take reference from the file ```src/sections/auth/auth-view-tsx```

2024-10-18 11:44 UTC, Akshay-Tomar-1135 commented on src/sections/user/user-edit-modal.tsx
> +  };
remove you custom snackbar implementation
and use globally declared one

2024-10-18 11:47 UTC, Akshay-Tomar-1135 commented on src/sections/user/user-edit-modal.tsx
> +  try {
don't use ```any``` type
instead in ```src/interface/userConfig.ts``` file define an interface and use that

define this api service/controller as others services implemented in ```src/service/userService.ts```

2024-10-18 11:48 UTC, Akshay-Tomar-1135 commented on src/sections/user/user-edit-modal.tsx
> +  </Snackbar>
you don't need to use custom snackbar

2024-10-18 11:53 UTC, Akshay-Tomar-1135 commented on src/sections/user/user-table-row.tsx
>  export type UserProps = {
you are also declaring same UserProps in ```src/sections/location/location-table-row.tsx```
do declare same types or interfaces repeatedly
instead declare one common interface or type in ```src/interface``` folder within relevant file, and export that interface or type, to make importable into any file

2024-10-18 11:55 UTC, Akshay-Tomar-1135 commented on src/sections/user/user-table-row.tsx
>  type UserTableRowProps = {
this is also repeated declaration
you can keep those attributes optional which are not used everywhere
thus declare only a common interface

2024-10-18 11:56 UTC, Akshay-Tomar-1135 commented on src/sections/user/view/user-view.tsx
>  import { _users } from 'src/_mock';
remove custome snackbar and use globally declared one

2024-10-18 11:57 UTC, Akshay-Tomar-1135 commented on src/sections/user/view/user-view.tsx
> +  const [snackbarSeverity, setSnackbarSeverity] = useState<'success' | 'error'>('success');
remove custom snackbar

2024-10-18 11:58 UTC, Akshay-Tomar-1135 commented on src/sections/user/view/user-view.tsx
> +  async function deleteUserContact(phoneNumber: string) {
declare this service in ```src/service``` folder within relevant file
and follow the similar template as other services declared in '''src/service/userSercvice.ts```

2024-10-18 11:59 UTC, Akshay-Tomar-1135 commented on src/sections/user/view/user-view.tsx
> +        const result = await deleteUserContact(userToDelete.role);
use service declared from ```src/service```

2024-10-18 12:00 UTC, Akshay-Tomar-1135 commented on src/sections/user/view/user-view.tsx
> +      <Snackbar
remove custom snackbar

2024-10-18 12:04 UTC, Akshay-Tomar-1135 requested changes
* use prettier extension for code formatting
* merge develop's updated changes to you branch and resolve conflict
* resolve the PR comments
* then push you changes again
* whoever between you and @Pankaj-Kumar110 resolves his PR comments first, his PR gets merged to develop first, then other one has to merge develop again to his branch and resolve conflict and then push changes, after that his PR will get merged, if having all PR comments resolved

2024-11-13 09:33 UTC, Akshay-Tomar-1135 commented on src/sections/location/location-table-row.tsx
> +};
Will be resolved in future updates

2024-11-13 09:51 UTC, Akshay-Tomar-1135 commented on src/sections/location/view/location-view.tsx
> +                ]}
you can declare these constants under ```src/_mock``` folder

2024-11-13 09:52 UTC, Akshay-Tomar-1135 commented on src/sections/profile/view/profile-view.tsx
> +  });
will be implemented in future updates

2024-11-13 09:54 UTC, Akshay-Tomar-1135 commented on src/sections/user/confirm-delete-dialog.tsx
use prettier for code formatting

2024-11-13 10:25 UTC, Akshay-Tomar-1135 commented on src/sections/user/user-table-row.tsx
>  type UserTableRowProps = {
still it is a repeated interface declaration
Declare this ```UserTableRowProps``` interface in ```src/inteface``` folder, and you can keep those fields optional which are not use everywhere.

2024-11-13 11:11 UTC, adityaS-99 commented on src/sections/user/user-table-row.tsx
>  type UserTableRowProps = {
Location section is still under development, location and user are totally different but for the time being to display dummy data I've kept the implementation same

2024-11-13 11:45 UTC, Akshay-Tomar-1135 commented on src/sections/user/confirm-delete-dialog.tsx
formatted

2024-11-13 11:56 UTC, merged