commit
Akshay-Tomar-1135/suraksha-frontend pull request #15
Opened 2024-10-13 06:29 UTC by Pankaj-Kumar110

User history + landing page fix

2024-10-18 10:50 UTC, Akshay-Tomar-1135 commented on src/_mock/_userHistory.ts
> +}
move this interface to interface folder in a new file named as 'userHistory.ts'.
Declare all interfaces or types related to 'User History' functionality there.

2024-10-18 10:53 UTC, Akshay-Tomar-1135 commented on src/components/Header.tsx
>              </ul>
this should be writtern as the following in line 67
```
<Button text="Get Started" onButtonClick={() => setOpenModal(true)} />
```

2024-10-18 10:57 UTC, Akshay-Tomar-1135 commented on src/components/Header.tsx
modify the following file like this
```
import { useState, useEffect } from 'react';
import Logo from '/assets/images/others/main-logo.png';
import { FaBars } from 'react-icons/fa';
import Box from '@mui/material/Box';
import { useRouter } from 'src/routes/hooks';
import { useAppDispatch } from 'src/store/reduxHooks';
import { setUserType } from 'src/store/features/userConfig/userConfigSlice';
import { UserTypes } from 'src/_mock';
import UserTypeModal from './UserTypeModal';
import Button from './Button';

export default function Header() {
  const [localUserType, setLocalUserType] = useState<UserTypes | null>(null);
  const [openModal, setOpenModal] = useState<boolean>(false);
  const router = useRouter();
  const [isMenuOpen, setIsMenuOpen] = useState(false); // State to track menu visibility

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen); // Toggle menu visibility
  };

  const dispatch = useAppDispatch();

  useEffect(() => {
    dispatch(setUserType(localUserType));
  }, [dispatch, localUserType]);

  useEffect(() => {
    console.log('userType in header ---', localUserType);
    if (!localUserType) return;
    router.push('/auth');
  }, [localUserType, router]);

  const navLinks = [
    { name: 'About', href: '#about' },
    { name: 'Features', href: '#features' },
    { name: 'Customers', href: '#customers' },
    { name: 'FAQ', href: '#faq' },
    { name: 'Feedback', href: '#feedback' },
  ];

  const renderNavLinks = () =>
    navLinks.map((link) => (
      <li key={link.name}>
        <a href={link.href}>{link.name}</a>
      </li>
    ));

  const menuList = (
    <>
      {renderNavLinks}
      <Button text="Get Started" onButtonClick={() => setOpenModal(true)} />
    </>
  );

  return (
    <>
      <UserTypeModal
        openModal={openModal}
        handleCloseModal={() => setOpenModal(false)}
        setUserType={setLocalUserType}
      />

      <header className="flex justify-between items-center px-6 py-4 backdrop-blur-md sticky top-0 z-20 bg-gradient-to-r from-[#E0E7FD] to-[#FDFEFF] shadow-md">
        <Box component="img" src={Logo} alt="Logo" className="cursor-pointer" />

        {/* Menu Icon for Mobile */}
        <FaBars className="block md:hidden cursor-pointer" onClick={toggleMenu} />

        {/* Desktop Navigation */}
        <nav className="hidden md:block">
          <ul className="flex gap-6 items-center">{menuList}</ul>
        </nav>

        {/* Mobile Navigation */}
        {isMenuOpen && (
          <nav className="md:hidden absolute top-full left-0 w-full bg-gradient-to-r from-[#E0E7FD] to-[#FDFEFF] shadow-md">
            <ul className="flex flex-col gap-4 p-6">{menuList}</ul>
          </nav>
        )}
      </header>
    </>
  );
}

```

2024-10-18 11:01 UTC, Akshay-Tomar-1135 commented on src/layouts/dashboard/nav.tsx
use tailwind CSS instead of inline syling

2024-10-18 11:02 UTC, Akshay-Tomar-1135 commented on src/layouts/simple/layout.tsx
> +            />),
use tailwind CSS

2024-10-18 11:06 UTC, Akshay-Tomar-1135 requested changes
develop branch has been updated
* take fresh pull from develop and merge develop's changes to your branch
* resolve conflicts
* resolve PR comments

2024-10-20 07:39 UTC, Pankaj-Kumar110 reviewed
Corrected all things which was requested like 
1. improved user History styling
2. added interface in separate file
3. fixed nav links

2024-10-20 13:19 UTC, Akshay-Tomar-1135 commented on src/_mock/_userHistory.ts
> +}
still this interface is not removed from here

2024-10-20 13:25 UTC, Akshay-Tomar-1135 commented on src/app.tsx
>  import store from './store/store';
why removed these changes, these were important

2024-10-20 13:33 UTC, Akshay-Tomar-1135 commented on src/app.tsx
>        </ThemeProvider>
only remove 
```
{githubButton}
```

2024-10-20 13:35 UTC, Akshay-Tomar-1135 commented on src/layouts/auth/layout.tsx
> +            />),
use tailwind css

2024-10-20 13:37 UTC, Akshay-Tomar-1135 commented on src/layouts/simple/layout.tsx
> +            />),
if you are giving custome value to height and width, then give it 'rem' not in 'px'.
may be that's the best practice.

2024-10-22 15:51 UTC, Akshay-Tomar-1135 commented on src/layouts/auth/layout.tsx
> +            leftArea: <img src={Logo} alt="Logo" className="h-[50] w-[50]" />,
what is 50 put some unit like ```rem```

2024-10-22 15:52 UTC, Akshay-Tomar-1135 requested changes
fix the one comment

2024-10-22 16:01 UTC, Akshay-Tomar-1135 approved these changes
all good

2024-10-22 16:05 UTC, merged